/* eslint-disable */
var PathKitInit = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(PathKitInit) {
  PathKitInit = PathKitInit || {};


null;var g;g||(g=typeof PathKitInit !== 'undefined' ? PathKitInit : {});var aa,ba;g.ready=new Promise(function(b,a){aa=b;ba=a});
(function(b){var a={};b.loadCmdsTypedArray=function(h){for(var k=0,l=0;l<h.length;l++)k+=h[l].length;if(a[k])var n=a[k];else n=new Float32Array(k),a[k]=n;var p=0;for(l=0;l<h.length;l++)for(var q=0;q<h[l].length;q++){var t=h[l][q];"string"===typeof t&&(t=b.SkBits2FloatUnsigned(parseInt(t)));n[p]=t;p++}h=b._malloc(n.length*n.BYTES_PER_ELEMENT);b.HEAPF32.set(n,h/n.BYTES_PER_ELEMENT);return[h,k]};b.FromCmds=function(h){h=b.loadCmdsTypedArray(h);var k=b._FromCmds(h[0],h[1]);b._free(h[0]);return k};var c,
d,e,f,m;b.cubicYFromX=function(h,k,l,n,p){c&&d===h&&e===k&&f===l&&m===n||(c&&c.delete(),c=new b._SkCubicMap([h,k],[l,n]),d=h,e=k,f=l,m=n);return c.computeYFromX(p)};b.cubicPtFromT=function(h,k,l,n,p){c&&d===h&&e===k&&f===l&&m===n||(c&&c.delete(),c=new b._SkCubicMap([h,k],[l,n]),d=h,e=k,f=l,m=n);return c.computePtFromT(p)}})(g);
(function(b){b.onRuntimeInitialized=function(){b.SkPath.prototype.addPath=function(){var a=arguments[0];if(1===arguments.length)this._addPath(a,1,0,0,0,1,0,0,0,1);else if(2===arguments.length){var c=arguments[1];this._addPath(a,c.a,c.c,c.e,c.b,c.d,c.f,0,0,1)}else if(7===arguments.length)c=arguments,this._addPath(a,c[1],c[3],c[5],c[2],c[4],c[6],0,0,1);else if(10===arguments.length)c=arguments,this._addPath(a,c[1],c[2],c[3],c[4],c[5],c[6],c[7],c[8],c[9]);else return console.La("addPath expected to take 1, 2, 7, or 10 args. Got "+
arguments.length),null;return this};b.SkPath.prototype.arc=function(a,c,d,e,f,m){this._arc(a,c,d,e,f,!!m);return this};b.SkPath.prototype.arcTo=function(a,c,d,e,f){this._arcTo(a,c,d,e,f);return this};b.SkPath.prototype.bezierCurveTo=function(a,c,d,e,f,m){this._cubicTo(a,c,d,e,f,m);return this};b.SkPath.prototype.close=function(){this._close();return this};b.SkPath.prototype.closePath=function(){this._close();return this};b.SkPath.prototype.conicTo=function(a,c,d,e,f){this._conicTo(a,c,d,e,f);return this};
b.SkPath.prototype.cubicTo=function(a,c,d,e,f,m){this._cubicTo(a,c,d,e,f,m);return this};b.SkPath.prototype.dash=function(a,c,d){return this._dash(a,c,d)?this:null};b.SkPath.prototype.ellipse=function(a,c,d,e,f,m,h,k){this._ellipse(a,c,d,e,f,m,h,!!k);return this};b.SkPath.prototype.lineTo=function(a,c){this._lineTo(a,c);return this};b.SkPath.prototype.moveTo=function(a,c){this._moveTo(a,c);return this};b.SkPath.prototype.op=function(a,c){return this._op(a,c)?this:null};b.SkPath.prototype.quadraticCurveTo=
function(a,c,d,e){this._quadTo(a,c,d,e);return this};b.SkPath.prototype.quadTo=function(a,c,d,e){this._quadTo(a,c,d,e);return this};b.SkPath.prototype.rect=function(a,c,d,e){this._rect(a,c,d,e);return this};b.SkPath.prototype.simplify=function(){return this._simplify()?this:null};b.SkPath.prototype.stroke=function(a){a=a||{};a.width=a.width||1;a.miter_limit=a.miter_limit||4;a.cap=a.cap||b.StrokeCap.BUTT;a.join=a.join||b.StrokeJoin.MITER;return this._stroke(a)?this:null};b.SkPath.prototype.transform=
function(){if(1===arguments.length)this._transform(arguments[0]);else if(9===arguments.length){var a=arguments;this._transform(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8])}else return console.La("transform expected to take 1 or 9 arguments. Got "+arguments.length),null;return this};b.SkPath.prototype.trim=function(a,c,d){return this._trim(a,c,!!d)?this:null}}})(g);var r={},v;for(v in g)g.hasOwnProperty(v)&&(r[v]=g[v]);var ca=!1,w=!1,da=!1,ea=!1;ca="object"===typeof window;w="function"===typeof importScripts;
da="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ea=!ca&&!da&&!w;var x="",fa,ha,y,ia,ja;
if(da)x=w?require("path").dirname(x)+"/":__dirname+"/",fa=function(b,a){ia||(ia=require("fs"));ja||(ja=require("path"));b=ja.normalize(b);return ia.readFileSync(b,a?null:"utf8")},y=function(b){b=fa(b,!0);b.buffer||(b=new Uint8Array(b));assert(b.buffer);return b},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",A),g.inspect=function(){return"[Emscripten Module object]"};else if(ea)"undefined"!=
typeof read&&(fa=function(b){return read(b)}),y=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");assert("object"===typeof b);return b},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ca||w)w?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptDir&&(x=_scriptDir),
0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="",fa=function(b){var a=new XMLHttpRequest;a.open("GET",b,!1);a.send(null);return a.responseText},w&&(y=function(b){var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)}),ha=function(b,a,c){var d=new XMLHttpRequest;d.open("GET",b,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?a(d.response):c()};d.onerror=c;d.send(null)};
var ka=g.print||console.log.bind(console),B=g.printErr||console.warn.bind(console);for(v in r)r.hasOwnProperty(v)&&(g[v]=r[v]);r=null;var la;g.wasmBinary&&(la=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var ma,na=!1;function assert(b,a){b||A("Assertion failed: "+a)}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function pa(b,a,c){var d=a+c;for(c=a;b[c]&&!(c>=d);)++c;if(16<c-a&&b.subarray&&oa)return oa.decode(b.subarray(a,c));for(d="";a<c;){var e=b[a++];if(e&128){var f=b[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var m=b[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|m:(e&7)<<18|f<<12|m<<6|b[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function qa(b,a,c){var d=D;if(0<c){c=a+c-1;for(var e=0;e<b.length;++e){var f=b.charCodeAt(e);if(55296<=f&&57343>=f){var m=b.charCodeAt(++e);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(a>=c)break;d[a++]=f}else{if(2047>=f){if(a+1>=c)break;d[a++]=192|f>>6}else{if(65535>=f){if(a+2>=c)break;d[a++]=224|f>>12}else{if(a+3>=c)break;d[a++]=240|f>>18;d[a++]=128|f>>12&63}d[a++]=128|f>>6&63}d[a++]=128|f&63}}d[a]=0}}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function sa(b,a){var c=b>>1;for(var d=c+a/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-b&&ra)return ra.decode(D.subarray(b,c));c="";for(d=0;!(d>=a/2);++d){var e=E[b+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function ua(b,a,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)E[a>>1]=b.charCodeAt(e),a+=2;E[a>>1]=0;return a-d}function va(b){return 2*b.length}
function wa(b,a){for(var c=0,d="";!(c>=a/4);){var e=F[b+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function xa(b,a,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var f=b.charCodeAt(e);if(55296<=f&&57343>=f){var m=b.charCodeAt(++e);f=65536+((f&1023)<<10)|m&1023}F[a>>2]=f;a+=4;if(a+4>c)break}F[a>>2]=0;return a-d}
function ya(b){for(var a=0,c=0;c<b.length;++c){var d=b.charCodeAt(c);55296<=d&&57343>=d&&++c;a+=4}return a}var za,Aa,D,E,ta,F,G,Ba,Ca,Da,Ea=[],Fa=[],Ga=[];function Ha(){var b=g.preRun.shift();Ea.unshift(b)}var H=0,Ia=null,Ja=null;g.preloadedImages={};g.preloadedAudios={};function A(b){if(g.onAbort)g.onAbort(b);B(b);na=!0;b=new WebAssembly.RuntimeError("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");ba(b);throw b;}
function Ka(){return I.startsWith("data:application/octet-stream;base64,")}var I="pathkit.wasm";if(!Ka()){var La=I;I=g.locateFile?g.locateFile(La,x):x+La}function Ma(){var b=I;try{if(b==I&&la)return new Uint8Array(la);if(y)return y(b);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}
function Na(){if(!la&&(ca||w)){if("function"===typeof fetch&&!I.startsWith("file://"))return fetch(I,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+I+"'";return b.arrayBuffer()}).catch(function(){return Ma()});if(ha)return new Promise(function(b,a){ha(I,function(c){b(new Uint8Array(c))},a)})}return Promise.resolve().then(function(){return Ma()})}
function Oa(b){for(;0<b.length;){var a=b.shift();if("function"==typeof a)a(g);else{var c=a.Va;"number"===typeof c?void 0===a.xa?Da.get(c)():Da.get(c)(a.xa):c(void 0===a.xa?null:a.xa)}}}var Pa={};function Qa(b){for(;b.length;){var a=b.pop();b.pop()(a)}}function J(b){return this.fromWireType(G[b>>2])}var K={},L={},Ra={};function Sa(b){if(void 0===b)return"_unknown";b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?"_"+b:b}
function Ta(b,a){b=Sa(b);return(new Function("body","return function "+b+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(a)}function Ua(b){var a=Error,c=Ta(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Va=void 0;function Wa(b){throw new Va(b);}function N(b,a,c){function d(h){h=c(h);h.length!==b.length&&Wa("Mismatched type converter count");for(var k=0;k<b.length;++k)O(b[k],h[k])}b.forEach(function(h){Ra[h]=a});var e=Array(a.length),f=[],m=0;a.forEach(function(h,k){L.hasOwnProperty(h)?e[k]=L[h]:(f.push(h),K.hasOwnProperty(h)||(K[h]=[]),K[h].push(function(){e[k]=L[h];++m;m===f.length&&d(e)}))});0===f.length&&d(e)}var Xa={};
function Ya(b){switch(b){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+b);}}var Za=void 0;function P(b){for(var a="";D[b];)a+=Za[D[b++]];return a}var Q=void 0;function R(b){throw new Q(b);}
function O(b,a,c){c=c||{};if(!("argPackAdvance"in a))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=a.name;b||R('type "'+d+'" must have a positive integer typeid pointer');if(L.hasOwnProperty(b)){if(c.Pa)return;R("Cannot register type '"+d+"' twice")}L[b]=a;delete Ra[b];K.hasOwnProperty(b)&&(a=K[b],delete K[b],a.forEach(function(e){e()}))}function $a(b){R(b.ea.ha.fa.name+" instance already deleted")}var ab=!1;function bb(){}
function cb(b){--b.count.value;0===b.count.value&&(b.ka?b.ma.la(b.ka):b.ha.fa.la(b.ga))}function db(b){if("undefined"===typeof FinalizationGroup)return db=function(a){return a},b;ab=new FinalizationGroup(function(a){for(var c=a.next();!c.done;c=a.next())c=c.value,c.ga?cb(c):console.warn("object already deleted: "+c.ga)});db=function(a){ab.register(a,a.ea,a.ea);return a};bb=function(a){ab.unregister(a.ea)};return db(b)}var eb=void 0,fb=[];
function gb(){for(;fb.length;){var b=fb.pop();b.ea.pa=!1;b["delete"]()}}function T(){}var hb={};function ib(b,a,c){if(void 0===b[a].ia){var d=b[a];b[a]=function(){b[a].ia.hasOwnProperty(arguments.length)||R("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+b[a].ia+")!");return b[a].ia[arguments.length].apply(this,arguments)};b[a].ia=[];b[a].ia[d.ua]=d}}
function jb(b,a,c){g.hasOwnProperty(b)?((void 0===c||void 0!==g[b].ia&&void 0!==g[b].ia[c])&&R("Cannot register public name '"+b+"' twice"),ib(g,b,b),g.hasOwnProperty(c)&&R("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[b].ia[c]=a):(g[b]=a,void 0!==c&&(g[b].Wa=c))}function kb(b,a,c,d,e,f,m,h){this.name=b;this.constructor=a;this.qa=c;this.la=d;this.na=e;this.Na=f;this.ta=m;this.Ka=h;this.Sa=[]}
function lb(b,a,c){for(;a!==c;)a.ta||R("Expected null or instance of "+c.name+", got an instance of "+a.name),b=a.ta(b),a=a.na;return b}function mb(b,a){if(null===a)return this.Ba&&R("null is not a valid "+this.name),0;a.ea||R('Cannot pass "'+U(a)+'" as a '+this.name);a.ea.ga||R("Cannot pass deleted object as a pointer of type "+this.name);return lb(a.ea.ga,a.ea.ha.fa,this.fa)}
function nb(b,a){if(null===a){this.Ba&&R("null is not a valid "+this.name);if(this.wa){var c=this.sa();null!==b&&b.push(this.la,c);return c}return 0}a.ea||R('Cannot pass "'+U(a)+'" as a '+this.name);a.ea.ga||R("Cannot pass deleted object as a pointer of type "+this.name);!this.va&&a.ea.ha.va&&R("Cannot convert argument of type "+(a.ea.ma?a.ea.ma.name:a.ea.ha.name)+" to parameter type "+this.name);c=lb(a.ea.ga,a.ea.ha.fa,this.fa);if(this.wa)switch(void 0===a.ea.ka&&R("Passing raw pointer to smart pointer is illegal"),
this.Ua){case 0:a.ea.ma===this?c=a.ea.ka:R("Cannot convert argument of type "+(a.ea.ma?a.ea.ma.name:a.ea.ha.name)+" to parameter type "+this.name);break;case 1:c=a.ea.ka;break;case 2:if(a.ea.ma===this)c=a.ea.ka;else{var d=a.clone();c=this.Ta(c,V(function(){d["delete"]()}));null!==b&&b.push(this.la,c)}break;default:R("Unsupporting sharing policy")}return c}
function ob(b,a){if(null===a)return this.Ba&&R("null is not a valid "+this.name),0;a.ea||R('Cannot pass "'+U(a)+'" as a '+this.name);a.ea.ga||R("Cannot pass deleted object as a pointer of type "+this.name);a.ea.ha.va&&R("Cannot convert argument of type "+a.ea.ha.name+" to parameter type "+this.name);return lb(a.ea.ga,a.ea.ha.fa,this.fa)}function pb(b,a,c){if(a===c)return b;if(void 0===c.na)return null;b=pb(b,a,c.na);return null===b?null:c.Ka(b)}var qb={};
function rb(b,a){for(void 0===a&&R("ptr should not be undefined");b.na;)a=b.ta(a),b=b.na;return qb[a]}function sb(b,a){a.ha&&a.ga||Wa("makeClassHandle requires ptr and ptrType");!!a.ma!==!!a.ka&&Wa("Both smartPtrType and smartPtr must be specified");a.count={value:1};return db(Object.create(b,{ea:{value:a}}))}
function W(b,a,c,d){this.name=b;this.fa=a;this.Ba=c;this.va=d;this.wa=!1;this.la=this.Ta=this.sa=this.Ia=this.Ua=this.Ra=void 0;void 0!==a.na?this.toWireType=nb:(this.toWireType=d?mb:ob,this.ja=null)}function tb(b,a,c){g.hasOwnProperty(b)||Wa("Replacing nonexistant public symbol");void 0!==g[b].ia&&void 0!==c?g[b].ia[c]=a:(g[b]=a,g[b].ua=c)}
function ub(b,a){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];b.includes("j")?(d=g["dynCall_"+b],d=c&&c.length?d.apply(null,[a].concat(c)):d.call(null,a)):d=Da.get(a).apply(null,c);return d}}function X(b,a){b=P(b);var c=b.includes("j")?ub(b,a):Da.get(a);"function"!==typeof c&&R("unknown function pointer with signature "+b+": "+a);return c}var vb=void 0;function wb(b){b=xb(b);var a=P(b);Y(b);return a}
function yb(b,a){function c(f){e[f]||L[f]||(Ra[f]?Ra[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};a.forEach(c);throw new vb(b+": "+d.map(wb).join([", "]));}function Bb(b,a){for(var c=[],d=0;d<b;d++)c.push(F[(a>>2)+d]);return c}
function Cb(b){var a=Function;if(!(a instanceof Function))throw new TypeError("new_ called with constructor type "+typeof a+" which is not a function");var c=Ta(a.name||"unknownFunctionName",function(){});c.prototype=a.prototype;c=new c;b=a.apply(c,b);return b instanceof Object?b:c}
function Db(b,a,c,d,e){var f=a.length;2>f&&R("argTypes array size mismatch! Must at least get return value and 'this' types!");var m=null!==a[1]&&null!==c,h=!1;for(c=1;c<a.length;++c)if(null!==a[c]&&void 0===a[c].ja){h=!0;break}var k="void"!==a[0].name,l="",n="";for(c=0;c<f-2;++c)l+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";b="return function "+Sa(b)+"("+l+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+b+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";h&&(b+="var destructors = [];\n");var p=h?"destructors":"null";l="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[R,d,e,Qa,a[0],a[1]];m&&(b+="var thisWired = classParam.toWireType("+p+", this);\n");for(c=0;c<f-2;++c)b+="var arg"+c+"Wired = argType"+c+".toWireType("+p+", arg"+c+"); // "+a[c+2].name+"\n",l.push("argType"+c),d.push(a[c+2]);m&&(n="thisWired"+(0<n.length?", ":"")+n);b+=(k?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(h)b+=
"runDestructors(destructors);\n";else for(c=m?1:2;c<a.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==a[c].ja&&(b+=f+"_dtor("+f+"); // "+a[c].name+"\n",l.push(f+"_dtor"),d.push(a[c].ja));k&&(b+="var ret = retType.fromWireType(rv);\nreturn ret;\n");l.push(b+"}\n");return Cb(l).apply(null,d)}var Eb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Fb(b){4<b&&0===--Z[b].Ca&&(Z[b]=void 0,Eb.push(b))}
function V(b){switch(b){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var a=Eb.length?Eb.pop():Z.length;Z[a]={Ca:1,value:b};return a}}function Gb(b,a,c){switch(a){case 0:return function(d){return this.fromWireType((c?Aa:D)[d])};case 1:return function(d){return this.fromWireType((c?E:ta)[d>>1])};case 2:return function(d){return this.fromWireType((c?F:G)[d>>2])};default:throw new TypeError("Unknown integer type: "+b);}}
function Hb(b,a){var c=L[b];void 0===c&&R(a+" has unknown type "+wb(b));return c}function U(b){if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b}function Ib(b,a){switch(a){case 2:return function(c){return this.fromWireType(Ba[c>>2])};case 3:return function(c){return this.fromWireType(Ca[c>>3])};default:throw new TypeError("Unknown float type: "+b);}}
function Jb(b,a,c){switch(a){case 0:return c?function(d){return Aa[d]}:function(d){return D[d]};case 1:return c?function(d){return E[d>>1]}:function(d){return ta[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return G[d>>2]};default:throw new TypeError("Unknown integer type: "+b);}}var Kb={};function Lb(b){var a=Kb[b];return void 0===a?P(b):a}var Mb=[];function Nb(b){b||R("Cannot use deleted val. handle = "+b);return Z[b].value}
function Ob(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Pb(b){var a=Mb.length;Mb.push(b);return a}function Qb(b,a){for(var c=Array(b),d=0;d<b;++d)c[d]=Hb(F[(a>>2)+d],"parameter "+d);return c}var Rb={},Sb=[null,[],[]];Va=g.InternalError=Ua("InternalError");for(var Tb=Array(256),Ub=0;256>Ub;++Ub)Tb[Ub]=String.fromCharCode(Ub);Za=Tb;Q=g.BindingError=Ua("BindingError");
T.prototype.isAliasOf=function(b){if(!(this instanceof T&&b instanceof T))return!1;var a=this.ea.ha.fa,c=this.ea.ga,d=b.ea.ha.fa;for(b=b.ea.ga;a.na;)c=a.ta(c),a=a.na;for(;d.na;)b=d.ta(b),d=d.na;return a===d&&c===b};
T.prototype.clone=function(){this.ea.ga||$a(this);if(this.ea.ra)return this.ea.count.value+=1,this;var b=db,a=Object,c=a.create,d=Object.getPrototypeOf(this),e=this.ea;b=b(c.call(a,d,{ea:{value:{count:e.count,pa:e.pa,ra:e.ra,ga:e.ga,ha:e.ha,ka:e.ka,ma:e.ma}}}));b.ea.count.value+=1;b.ea.pa=!1;return b};T.prototype["delete"]=function(){this.ea.ga||$a(this);this.ea.pa&&!this.ea.ra&&R("Object already scheduled for deletion");bb(this);cb(this.ea);this.ea.ra||(this.ea.ka=void 0,this.ea.ga=void 0)};
T.prototype.isDeleted=function(){return!this.ea.ga};T.prototype.deleteLater=function(){this.ea.ga||$a(this);this.ea.pa&&!this.ea.ra&&R("Object already scheduled for deletion");fb.push(this);1===fb.length&&eb&&eb(gb);this.ea.pa=!0;return this};W.prototype.Oa=function(b){this.Ia&&(b=this.Ia(b));return b};W.prototype.Ga=function(b){this.la&&this.la(b)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=J;W.prototype.deleteObject=function(b){if(null!==b)b["delete"]()};
W.prototype.fromWireType=function(b){function a(){return this.wa?sb(this.fa.qa,{ha:this.Ra,ga:c,ma:this,ka:b}):sb(this.fa.qa,{ha:this,ga:b})}var c=this.Oa(b);if(!c)return this.Ga(b),null;var d=rb(this.fa,c);if(void 0!==d){if(0===d.ea.count.value)return d.ea.ga=c,d.ea.ka=b,d.clone();d=d.clone();this.Ga(b);return d}d=this.fa.Na(c);d=hb[d];if(!d)return a.call(this);d=this.va?d.Ja:d.pointerType;var e=pb(c,this.fa,d.fa);return null===e?a.call(this):this.wa?sb(d.fa.qa,{ha:d,ga:e,ma:this,ka:b}):sb(d.fa.qa,
{ha:d,ga:e})};g.getInheritedInstanceCount=function(){return Object.keys(qb).length};g.getLiveInheritedInstances=function(){var b=[],a;for(a in qb)qb.hasOwnProperty(a)&&b.push(qb[a]);return b};g.flushPendingDeletes=gb;g.setDelayFunction=function(b){eb=b;fb.length&&eb&&eb(gb)};vb=g.UnboundTypeError=Ua("UnboundTypeError");g.count_emval_handles=function(){for(var b=0,a=5;a<Z.length;++a)void 0!==Z[a]&&++b;return b};g.get_first_emval=function(){for(var b=5;b<Z.length;++b)if(void 0!==Z[b])return Z[b];return null};
var Wb={r:function(b){var a=Pa[b];delete Pa[b];var c=a.elements,d=c.length,e=c.map(function(h){return h.Aa}).concat(c.map(function(h){return h.Ea})),f=a.sa,m=a.la;N([b],e,function(h){c.forEach(function(k,l){var n=h[l],p=k.ya,q=k.za,t=h[l+d],u=k.Da,M=k.Fa;k.read=function(z){return n.fromWireType(p(q,z))};k.write=function(z,S){var C=[];u(M,z,t.toWireType(C,S));Qa(C)}});return[{name:a.name,fromWireType:function(k){for(var l=Array(d),n=0;n<d;++n)l[n]=c[n].read(k);m(k);return l},toWireType:function(k,
l){if(d!==l.length)throw new TypeError("Incorrect number of tuple elements for "+a.name+": expected="+d+", actual="+l.length);for(var n=f(),p=0;p<d;++p)c[p].write(n,l[p]);null!==k&&k.push(m,n);return n},argPackAdvance:8,readValueFromPointer:J,ja:m}]})},u:function(b){var a=Xa[b];delete Xa[b];var c=a.sa,d=a.la,e=a.Ha,f=e.map(function(m){return m.Aa}).concat(e.map(function(m){return m.Ea}));N([b],f,function(m){var h={};e.forEach(function(k,l){var n=m[l],p=k.ya,q=k.za,t=m[l+e.length],u=k.Da,M=k.Fa;h[k.Ma]=
{read:function(z){return n.fromWireType(p(q,z))},write:function(z,S){var C=[];u(M,z,t.toWireType(C,S));Qa(C)}}});return[{name:a.name,fromWireType:function(k){var l={},n;for(n in h)l[n]=h[n].read(k);d(k);return l},toWireType:function(k,l){for(var n in h)if(!(n in l))throw new TypeError('Missing field:  "'+n+'"');var p=c();for(n in h)h[n].write(p,l[n]);null!==k&&k.push(d,p);return p},argPackAdvance:8,readValueFromPointer:J,ja:d}]})},z:function(){},F:function(b,a,c,d,e){var f=Ya(c);a=P(a);O(b,{name:a,
fromWireType:function(m){return!!m},toWireType:function(m,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(m){if(1===c)var h=Aa;else if(2===c)h=E;else if(4===c)h=F;else throw new TypeError("Unknown boolean type size: "+a);return this.fromWireType(h[m>>f])},ja:null})},l:function(b,a,c,d,e,f,m,h,k,l,n,p,q){n=P(n);f=X(e,f);h&&(h=X(m,h));l&&(l=X(k,l));q=X(p,q);var t=Sa(n);jb(t,function(){yb("Cannot construct "+n+" due to unbound types",[d])});N([b,a,c],d?[d]:[],function(u){u=u[0];if(d){var M=
u.fa;var z=M.qa}else z=T.prototype;u=Ta(t,function(){if(Object.getPrototypeOf(this)!==S)throw new Q("Use 'new' to construct "+n);if(void 0===C.oa)throw new Q(n+" has no accessible constructor");var zb=C.oa[arguments.length];if(void 0===zb)throw new Q("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(C.oa).toString()+") parameters instead!");return zb.apply(this,arguments)});var S=Object.create(z,{constructor:{value:u}});u.prototype=S;
var C=new kb(n,u,S,q,M,f,h,l);M=new W(n,C,!0,!1);z=new W(n+"*",C,!1,!1);var Ab=new W(n+" const*",C,!1,!0);hb[b]={pointerType:z,Ja:Ab};tb(t,u);return[M,z,Ab]})},i:function(b,a,c,d,e,f){assert(0<a);var m=Bb(a,c);e=X(d,e);var h=[f],k=[];N([],[b],function(l){l=l[0];var n="constructor "+l.name;void 0===l.fa.oa&&(l.fa.oa=[]);if(void 0!==l.fa.oa[a-1])throw new Q("Cannot register multiple constructors with identical number of parameters ("+(a-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
l.fa.oa[a-1]=function(){yb("Cannot construct "+l.name+" due to unbound types",m)};N([],m,function(p){l.fa.oa[a-1]=function(){arguments.length!==a-1&&R(n+" called with "+arguments.length+" arguments, expected "+(a-1));k.length=0;h.length=a;for(var q=1;q<a;++q)h[q]=p[q].toWireType(k,arguments[q-1]);q=e.apply(null,h);Qa(k);return p[0].fromWireType(q)};return[]});return[]})},a:function(b,a,c,d,e,f,m,h){var k=Bb(c,d);a=P(a);f=X(e,f);N([],[b],function(l){function n(){yb("Cannot call "+p+" due to unbound types",
k)}l=l[0];var p=l.name+"."+a;h&&l.fa.Sa.push(a);var q=l.fa.qa,t=q[a];void 0===t||void 0===t.ia&&t.className!==l.name&&t.ua===c-2?(n.ua=c-2,n.className=l.name,q[a]=n):(ib(q,a,p),q[a].ia[c-2]=n);N([],k,function(u){u=Db(p,u,l,f,m);void 0===q[a].ia?(u.ua=c-2,q[a]=u):q[a].ia[c-2]=u;return[]});return[]})},I:function(b,a,c){b=P(b);N([],[a],function(d){d=d[0];g[b]=d.fromWireType(c);return[]})},E:function(b,a){a=P(a);O(b,{name:a,fromWireType:function(c){var d=Z[c].value;Fb(c);return d},toWireType:function(c,
d){return V(d)},argPackAdvance:8,readValueFromPointer:J,ja:null})},h:function(b,a,c,d){function e(){}c=Ya(c);a=P(a);e.values={};O(b,{name:a,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:function(f,m){return m.value},argPackAdvance:8,readValueFromPointer:Gb(a,c,d),ja:null});jb(a,e)},k:function(b,a,c){var d=Hb(b,"enum");a=P(a);b=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ta(d.name+"_"+a,function(){})}});b.values[c]=
d;b[a]=d},p:function(b,a,c){c=Ya(c);a=P(a);O(b,{name:a,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+U(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Ib(a,c),ja:null})},f:function(b,a,c,d,e,f){var m=Bb(a,c);b=P(b);e=X(d,e);jb(b,function(){yb("Cannot call "+b+" due to unbound types",m)},a-1);N([],m,function(h){h=[h[0],null].concat(h.slice(1));tb(b,Db(b,h,null,e,f),a-1);return[]})},
e:function(b,a,c,d,e){function f(l){return l}a=P(a);-1===e&&(e=4294967295);var m=Ya(c);if(0===d){var h=32-8*c;f=function(l){return l<<h>>>h}}var k=a.includes("unsigned");O(b,{name:a,fromWireType:f,toWireType:function(l,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+U(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+U(n)+'" from JS side to C/C++ side to an argument of type "'+a+'", which is outside the valid range ['+d+", "+e+"]!");
return k?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:Jb(a,m,0!==d),ja:null})},b:function(b,a,c){function d(f){f>>=2;var m=G;return new e(za,m[f+1],m[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][a];c=P(c);O(b,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Pa:!0})},q:function(b,a){a=P(a);var c="std::string"===a;O(b,{name:a,fromWireType:function(d){var e=G[d>>2];if(c)for(var f=d+4,m=0;m<=e;++m){var h=d+4+m;if(m==e||0==
D[h]){f=f?pa(D,f,h-f):"";if(void 0===k)var k=f;else k+=String.fromCharCode(0),k+=f;f=h+1}}else{k=Array(e);for(m=0;m<e;++m)k[m]=String.fromCharCode(D[d+4+m]);k=k.join("")}Y(d);return k},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||R("Cannot pass non-string to std::string");var m=(c&&f?function(){for(var l=0,n=0;n<e.length;++n){var p=e.charCodeAt(n);55296<=p&&57343>=
p&&(p=65536+((p&1023)<<10)|e.charCodeAt(++n)&1023);127>=p?++l:l=2047>=p?l+2:65535>=p?l+3:l+4}return l}:function(){return e.length})(),h=Vb(4+m+1);G[h>>2]=m;if(c&&f)qa(e,h+4,m+1);else if(f)for(f=0;f<m;++f){var k=e.charCodeAt(f);255<k&&(Y(h),R("String has UTF-16 code units that do not fit in 8 bits"));D[h+4+f]=k}else for(f=0;f<m;++f)D[h+4+f]=e[f];null!==d&&d.push(Y,h);return h},argPackAdvance:8,readValueFromPointer:J,ja:function(d){Y(d)}})},m:function(b,a,c){c=P(c);if(2===a){var d=sa;var e=ua;var f=
va;var m=function(){return ta};var h=1}else 4===a&&(d=wa,e=xa,f=ya,m=function(){return G},h=2);O(b,{name:c,fromWireType:function(k){for(var l=G[k>>2],n=m(),p,q=k+4,t=0;t<=l;++t){var u=k+4+t*a;if(t==l||0==n[u>>h])q=d(q,u-q),void 0===p?p=q:(p+=String.fromCharCode(0),p+=q),q=u+a}Y(k);return p},toWireType:function(k,l){"string"!==typeof l&&R("Cannot pass non-string to C++ string type "+c);var n=f(l),p=Vb(4+n+a);G[p>>2]=n>>h;e(l,p+4,n+a);null!==k&&k.push(Y,p);return p},argPackAdvance:8,readValueFromPointer:J,
ja:function(k){Y(k)}})},t:function(b,a,c,d,e,f){Pa[b]={name:P(a),sa:X(c,d),la:X(e,f),elements:[]}},s:function(b,a,c,d,e,f,m,h,k){Pa[b].elements.push({Aa:a,ya:X(c,d),za:e,Ea:f,Da:X(m,h),Fa:k})},v:function(b,a,c,d,e,f){Xa[b]={name:P(a),sa:X(c,d),la:X(e,f),Ha:[]}},j:function(b,a,c,d,e,f,m,h,k,l){Xa[b].Ha.push({Ma:P(a),Aa:c,ya:X(d,e),za:f,Ea:m,Da:X(h,k),Fa:l})},G:function(b,a){a=P(a);O(b,{Qa:!0,name:a,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},d:function(b,a,c,d){b=Mb[b];a=
Nb(a);c=Lb(c);b(a,c,null,d)},J:Fb,x:function(b){if(0===b)return V(Ob());b=Lb(b);return V(Ob()[b])},c:function(b,a){a=Qb(b,a);for(var c=a[0],d=c.name+"_$"+a.slice(1).map(function(l){return l.name}).join("_")+"$",e=["retType"],f=[c],m="",h=0;h<b-1;++h)m+=(0!==h?", ":"")+"arg"+h,e.push("argType"+h),f.push(a[1+h]);d="return function "+Sa("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var k=0;for(h=0;h<b-1;++h)d+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+(k?"+"+k:"")+");\n",
k+=a[h+1].argPackAdvance;d+="    var rv = handle[name]("+m+");\n";for(h=0;h<b-1;++h)a[h+1].deleteObject&&(d+="    argType"+h+".deleteObject(arg"+h+");\n");c.Qa||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");b=Cb(e).apply(null,f);return Pb(b)},n:function(b){4<b&&(Z[b].Ca+=1)},w:function(b,a,c,d){b=Nb(b);var e=Rb[a];if(!e){e="";for(var f=0;f<a;++f)e+=(0!==f?", ":"")+"arg"+f;var m="return function emval_allocator_"+a+"(constructor, argTypes, args) {\n";for(f=0;f<a;++f)m+=
"var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",m+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(Hb,g,V);Rb[a]=e}return e(b,c,d)},K:function(){return V([])},D:function(b){return V(Lb(b))},H:function(b,a){b=Hb(b,"_emval_take_value");b=b.readValueFromPointer(a);
return V(b)},g:function(){A()},B:function(){A("OOM")},C:function(){return 0},y:function(){},o:function(b,a,c,d){for(var e=0,f=0;f<c;f++){for(var m=F[a+8*f>>2],h=F[a+(8*f+4)>>2],k=0;k<h;k++){var l=D[m+k],n=Sb[b];0===l||10===l?((1===b?ka:B)(pa(n,0)),n.length=0):n.push(l)}e+=h}F[d>>2]=e;return 0},A:function(){}};
(function(){function b(e){g.asm=e.exports;ma=g.asm.L;za=e=ma.buffer;g.HEAP8=Aa=new Int8Array(e);g.HEAP16=E=new Int16Array(e);g.HEAP32=F=new Int32Array(e);g.HEAPU8=D=new Uint8Array(e);g.HEAPU16=ta=new Uint16Array(e);g.HEAPU32=G=new Uint32Array(e);g.HEAPF32=Ba=new Float32Array(e);g.HEAPF64=Ca=new Float64Array(e);Da=g.asm._;Fa.unshift(g.asm.M);H--;g.monitorRunDependencies&&g.monitorRunDependencies(H);0==H&&(null!==Ia&&(clearInterval(Ia),Ia=null),Ja&&(e=Ja,Ja=null,e()))}function a(e){b(e.instance)}function c(e){return Na().then(function(f){return WebAssembly.instantiate(f,
d)}).then(e,function(f){B("failed to asynchronously prepare wasm: "+f);A(f)})}var d={a:Wb};H++;g.monitorRunDependencies&&g.monitorRunDependencies(H);if(g.instantiateWasm)try{return g.instantiateWasm(d,b)}catch(e){return B("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return la||"function"!==typeof WebAssembly.instantiateStreaming||Ka()||I.startsWith("file://")||"function"!==typeof fetch?c(a):fetch(I,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(a,function(f){B("wasm streaming compile failed: "+f);B("falling back to ArrayBuffer instantiation");return c(a)})})})().catch(ba);return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.M).apply(null,arguments)};g.__Z6ToCmdsRK6SkPath=function(){return(g.__Z6ToCmdsRK6SkPath=g.asm.N).apply(null,arguments)};g.__Z8FromCmdsmi=function(){return(g.__Z8FromCmdsmi=g.asm.O).apply(null,arguments)};g.__Z7NewPathv=function(){return(g.__Z7NewPathv=g.asm.P).apply(null,arguments)};
g.__Z8CopyPathRK6SkPath=function(){return(g.__Z8CopyPathRK6SkPath=g.asm.Q).apply(null,arguments)};g.__Z6EqualsRK6SkPathS1_=function(){return(g.__Z6EqualsRK6SkPathS1_=g.asm.R).apply(null,arguments)};g.__Z11ToSVGStringRK6SkPath=function(){return(g.__Z11ToSVGStringRK6SkPath=g.asm.S).apply(null,arguments)};
g.__Z13FromSVGStringNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE=function(){return(g.__Z13FromSVGStringNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE=g.asm.T).apply(null,arguments)};g.__Z13ApplySimplifyR6SkPath=function(){return(g.__Z13ApplySimplifyR6SkPath=g.asm.U).apply(null,arguments)};g.__Z11ApplyPathOpR6SkPathRKS_8SkPathOp=function(){return(g.__Z11ApplyPathOpR6SkPathRKS_8SkPathOp=g.asm.V).apply(null,arguments)};
g.__Z10MakeFromOpRK6SkPathS1_8SkPathOp=function(){return(g.__Z10MakeFromOpRK6SkPathS1_8SkPathOp=g.asm.W).apply(null,arguments)};g.__Z14ResolveBuilderR11SkOpBuilder=function(){return(g.__Z14ResolveBuilderR11SkOpBuilder=g.asm.X).apply(null,arguments)};g.__Z8ToCanvasRK6SkPathN10emscripten3valE=function(){return(g.__Z8ToCanvasRK6SkPathN10emscripten3valE=g.asm.Y).apply(null,arguments)};g.__Z8ToPath2DRK6SkPath=function(){return(g.__Z8ToPath2DRK6SkPath=g.asm.Z).apply(null,arguments)};
var Y=g._free=function(){return(Y=g._free=g.asm.$).apply(null,arguments)},Vb=g._malloc=function(){return(Vb=g._malloc=g.asm.aa).apply(null,arguments)},xb=g.___getTypeName=function(){return(xb=g.___getTypeName=g.asm.ba).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.ca).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.da).apply(null,arguments)};var Xb;
Ja=function Yb(){Xb||Zb();Xb||(Ja=Yb)};
function Zb(){function b(){if(!Xb&&(Xb=!0,g.calledRun=!0,!na)){Oa(Fa);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var a=g.postRun.shift();Ga.unshift(a)}Oa(Ga)}}if(!(0<H)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ha();Oa(Ea);0<H||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=Zb;
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Zb();


  return PathKitInit.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = PathKitInit;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return PathKitInit; });
else if (typeof exports === 'object')
  exports["PathKitInit"] = PathKitInit;
