name: Build Site

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@main
        with:
          node-version: 16.18.1
      - run: yarn install --ignore-optional
      - run: yarn build:site
