name: Build

on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@main
        with:
          node-version: 14
      - run: yarn
      - run: yarn build:desktop
