name: Mobile Detox tests

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@main

      - name: Configure detox
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Install app dependencies
        run: |
          yarn install --frozen-lockfile --network-timeout 1000000
          cd packages/app-mobile/ios
          pod install
          cd ..

      - name: Build iOS app
        run: |
          cd packages/app-mobile/ios
          yarn detox:build -- -- --record-logs all

      - name: Run iOS E2E test suite
        run: |
          cd packages/app-mobile/ios
          yarn detox:test
