name: Unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:16.18.1
      env:
        CI: true

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --ignore-optional
      - run: yarn test
