name: Unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:14.17
      env:
        CI: true

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test graphql
